### PR TITLE
Adding Plex to theme

### PR DESCRIPTION
**Pull request by jr0dd**
Adding plex to theme for those that prefer plex over kodi.

### CODE REVIEW

**Comment by jr0dd** [comment]
Looks like this may have been over-looked.

**Comment by robertybob** [comment]
Does this look ok @HerbFargus ?

**Comment by joolswills** [comment]
@HerbFargus not sure if we should include this - are we intending to include everything in carbon or just most used stuff? Also since we include it in ports by default, it might be enough for include this on the wiki for those that want it launching from a "system".

I'm leaning towards not including this currently.

**Comment by HerbFargus** [comment]
I'd just as well only include stuff retropie ships with. Otherwise where do we draw the line with systems?

**Comment by jr0dd** [comment]
closing this

**Pull request closed without merging**
